#!/bin/sh

if [ "x$PIPENV_ACTIVE" != x ]
then
    echo "Fatal: MUST NOT be running in pipenv."
    exit 2
fi

if [ "x$VIRTUAL_ENV" != x ]
then
    echo "Fatal: MUST NOT be running in virtualenv."
    exit 2
fi

abs_scriptdir="$(cd "$(dirname "$0")" && pwd)"
abs_topdir="$(cd "$(dirname "$abs_scriptdir")" && pwd)"

device_connected=false
for idProduct in 0030 0031 0032
do
    if lsusb -d "05fc:${idProduct}"
    then
	device_connected=true
	break
    fi
done

if "$device_connected"
then
    echo "Device is connected. Good."
else
    echo "Fatal: No device connected."
    exit 1
fi

set -ex

cd "$abs_topdir"

sudo_script_post_install_arg="--sudo-script=sudo-script-post-pip-install.sh"
sudo_script_pre_uninstall_arg="--sudo-script=sudo-script-pre-pip-uninstall.sh"

sudo rm -f  "/usr/local/bin"/socranop-* "/usr/local/share/dbus-1/services"/socranop*
sudo rm -rf "/usr/local/lib"/python*/{dist,site}-packages/socranop*

rm -f  "$HOME/.local/bin"/socranop-* "$HOME/.local/share/dbus-1/services"/socranop*
rm -rf "$HOME/.local/lib"/python*/{dist,site}-packages/socranop*

if socranop-ctl --version >/dev/null 2>&1
then
    echo "Fatal: There is still socranop-ctl in the PATH."
    exit 2
fi

test_install_pipenv_dev() {
    local virtual_env
    virtual_env="$(pipenv run printenv | sed -n 's|^VIRTUAL_ENV=||p')"
    rm -f  "$virtual_env"/bin/socranop-*
    rm -rf "$virtual_env"/lib/python*/{dist,site}-packages/socranop*
    pipenv install --dev
    ./tools/link_system_libs
    pipenv run "$virtual_env/bin/socranop-installtool" post-pip-install $sudo_script_post_install_arg
    cat sudo-script-post-pip-install.sh
    pipenv run "$virtual_env/bin/socranop-ctl" --list
    pipenv run "$virtual_env/bin/socranop-ctl" --set 0
    pipenv run "$virtual_env/bin/socranop-ctl" --list
    pipenv run "$virtual_env/bin/socranop-ctl" --set 1
    pipenv run "$virtual_env/bin/socranop-ctl" --list
    pipenv run "$virtual_env/bin/socranop-ctl" --set 2
    pipenv run "$virtual_env/bin/socranop-ctl" --list
    pipenv run "$virtual_env/bin/socranop-ctl" --set 3
    pipenv run "$virtual_env/bin/socranop-installtool" pre-pip-uninstall $sudo_script_pre_uninstall_arg
    cat sudo-script-pre-pip-uninstall.sh
}

test_install_home() {
    saved_PATH="$PATH"
    saved_PYTHONPATH="$PYTHONPATH"

    pip install --user "$wheel"
    socranop-installtool post-pip-install $sudo_script_post_install_arg
    if [ -f sudo-script-post-pip-install.sh ]; then cat sudo-script-post-pip-install.sh; fi
    socranop-ctl --list
    socranop-ctl --set 0
    socranop-ctl --list
    socranop-ctl --set 1
    socranop-ctl --list
    socranop-ctl --set 2
    socranop-ctl --list
    socranop-ctl --set 3
    socranop-installtool pre-pip-uninstall $sudo_script_pre_uninstall_arg
    if [ -f sudo-script-pre-pip-uninstall.sh ]; then cat sudo-script-pre-pip-uninstall.sh; fi
    pip --verbose uninstall --yes socranop

    PATH="$saved_PATH"
    export PATH
    PYTHONPATH="$saved_PYTHONPATH"
    export PYTHONPATH
}

test_sudo_usr_local() {
    saved_PATH="$PATH"
    saved_PYTHONPATH="$PYTHONPATH"

    prefix="/usr/local"
    bindir="$prefix/bin"
    PATH="$bindir:$PATH"
    export PATH
    sudo pip install "$wheel"
    site_packages="$(ls -1d "$prefix"/lib/python*/{dist,site}-packages | head -n1)"
    PYTHONPATH="$site_packages"
    export PYTHONPATH
    sudo "$bindir/socranop-installtool" post-pip-install
    socranop-ctl --list
    socranop-ctl --set 0
    socranop-ctl --list
    socranop-ctl --set 1
    socranop-ctl --list
    socranop-ctl --set 2
    socranop-ctl --list
    socranop-ctl --set 3
    sudo "$bindir/socranop-installtool" pre-pip-uninstall
    sudo pip --verbose uninstall --yes socranop

    PATH="$saved_PATH"
    export PATH
    PYTHONPATH="$saved_PYTHONPATH"
    export PYTHONPATH
}

test_chroot_usr() {
    saved_PATH="$PATH"
    saved_PYTHONPATH="$PYTHONPATH"

    chroot="$PWD/__chroot_usr"
    prefix="/usr"
    bindir="$prefix/bin"
    PATH="$chroot$bindir:$PATH"
    export PATH
    rm -rf "$chroot"
    pip install --root "$chroot" --prefix "$prefix" "$wheel"
    site_packages="$(ls -1d "$chroot$prefix"/lib/python*/{dist,site}-packages | head -n1)"
    PYTHONPATH="$site_packages"
    export PYTHONPATH
    "$chroot$bindir/socranop-installtool" package-build-install --chroot="$chroot"
    # socranop-ctl --list
    # socranop-ctl --set 0
    # socranop-ctl --list
    # socranop-ctl --set 1
    # socranop-ctl --list
    # socranop-ctl --set 2
    # socranop-ctl --list
    # socranop-ctl --set 3

    echo "Removing chroot $chroot"
    rm -rf "$chroot"

    PATH="$saved_PATH"
    export PATH
    PYTHONPATH="$saved_PYTHONPATH"
    export PYTHONPATH
}

test_install_pipenv_dev

pipenv run ./tools/dist
wheel="$(ls -1 dist/socranop-*.whl | head -n1)"

test_install_home

test_chroot_usr

test_sudo_usr_local
