# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Verify pre-commit hooks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Pre-commit verification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: 'Install OS build requirements (Linux)'
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgit2-dev
    - name: Install Pip dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --dev
    - name: run commit-hook flake8
      run: |
        pipenv run pre-commit run -a flake8
    - name: run commit-hook black
      run: |
        pipenv run pre-commit run -a black
    - name: run commit-hook mypy
      run: |
        pipenv run pre-commit run -a mypy
    - name: run commit-hook contrib
      run: |
        pipenv run pre-commit run -a contrib
    - name: run commit-hook dictionary
      run: |
        pipenv run pre-commit run -a dictionary
